#!/usr/bin/env python3
"""
∞ Bryan's Marketing Automation Setup - Complete & Ready ∞

Pattern: SETUP × MARKETING × AUTOMATION × ONE
Frequency: 999 Hz (AEYON) × 777 Hz (META) × 530 Hz (ALL GUARDIANS)
Guardians: AEYON (999 Hz) + META (777 Hz) + ALL GUARDIANS (530 Hz)
Love Coefficient: ∞
∞ AbëONE ∞

ZERO EFFORT: Run once, everything works
ZERO TRUST: Validates all credentials before proceeding
"""

import json
import os
import sys
from pathlib import Path
from typing import Dict, List, Optional

# Add abekeys to path
sys.path.insert(0, str(Path(__file__).parent))
from abekeys import Abekeys, get


class MarketingAutomationSetup:
    """Complete Marketing Automation Setup for Bryan"""
    
    REQUIRED_SERVICES = {
        "google_ads": {
            "required_keys": ["client_id", "client_secret", "refresh_token", "developer_token", "customer_id"],
            "description": "Google Ads API for campaign management"
        },
        "sendgrid": {
            "required_keys": ["api_key"],
            "description": "SendGrid for email marketing"
        },
        "stripe": {
            "required_keys": ["api_key"],  # Flexible: accepts api_key OR secret_key OR both
            "description": "Stripe for payment processing"
        }
    }
    
    OPTIONAL_SERVICES = {
        "mailchimp": {"description": "Mailchimp email marketing"},
        "facebook": {"description": "Facebook Ads API"},
        "shopify": {"description": "Shopify e-commerce"},
    }
    
    def __init__(self):
        self.abekeys = Abekeys()
        self.credentials: Dict[str, Dict] = {}
        self.missing: List[str] = []
        self.ready: bool = False
    
    def validate_all(self) -> bool:
        """Validate all required credentials - ZERO TRUST"""
        print("🔐 Validating Marketing Automation Credentials...\n")
        
        all_valid = True
        
        # Check required services
        for service, config in self.REQUIRED_SERVICES.items():
            print(f"  Checking {service}...", end=" ")
            cred = self.abekeys.get(service)
            
            if not cred:
                print("❌ NOT FOUND")
                self.missing.append(service)
                all_valid = False
                continue
            
            # Validate required keys (flexible for stripe)
            missing_keys = []
            for key in config["required_keys"]:
                # For stripe, accept api_key OR secret_key
                if service == "stripe" and key == "api_key":
                    if not cred.get("api_key") and not cred.get("secret_key"):
                        missing_keys.append("api_key or secret_key")
                elif not cred.get(key):
                    missing_keys.append(key)
            
            if missing_keys:
                print(f"❌ MISSING KEYS: {', '.join(missing_keys)}")
                self.missing.append(f"{service} ({', '.join(missing_keys)})")
                all_valid = False
            else:
                print("✅ READY")
                self.credentials[service] = cred.data
        
        # Check optional services
        print("\n  Optional services:")
        for service, config in self.OPTIONAL_SERVICES.items():
            cred = self.abekeys.get(service)
            if cred:
                print(f"    ✅ {service} - Available")
                self.credentials[service] = cred.data
            else:
                print(f"    ⚪ {service} - Not configured")
        
        self.ready = all_valid
        return all_valid
    
    def generate_env_file(self, output_path: Optional[Path] = None) -> str:
        """Generate .env file with all credentials - ZERO EFFORT"""
        if not self.ready:
            raise ValueError("Credentials not validated. Run validate_all() first.")
        
        if output_path is None:
            output_path = Path.cwd() / ".env.marketing"
        
        env_lines = [
            "# Marketing Automation Environment Variables",
            "# Generated by AbëKEYs Marketing Automation Setup",
            "# ZERO TRUST: Never commit this file to git",
            "",
        ]
        
        for service, cred_data in self.credentials.items():
            env_lines.append(f"# {service.upper()}")
            prefix = service.upper().replace('-', '_')
            for key, value in cred_data.items():
                env_key = f"{prefix}_{key.upper()}"
                env_lines.append(f"{env_key}={value}")
            env_lines.append("")
        
        env_content = "\n".join(env_lines)
        
        # Write file
        output_path.write_text(env_content)
        output_path.chmod(0o600)  # Secure permissions
        
        return str(output_path)
    
    def generate_python_config(self, output_path: Optional[Path] = None) -> str:
        """Generate Python config file - ZERO EFFORT"""
        if not self.ready:
            raise ValueError("Credentials not validated. Run validate_all() first.")
        
        if output_path is None:
            output_path = Path.cwd() / "marketing_config.py"
        
        config_lines = [
            "# Marketing Automation Configuration",
            "# Generated by AbëKEYs Marketing Automation Setup",
            "# ZERO TRUST: Never commit this file to git",
            "",
            "from pathlib import Path",
            "from scripts.abekeys.abekeys import get",
            "",
            "# Load credentials from AbëKEYs vault",
            "",
        ]
        
        for service in self.credentials.keys():
            var_name = service.upper().replace('-', '_')
            config_lines.append(f"{var_name} = get('{service}')")
        
        config_lines.extend([
            "",
            "# Quick access functions",
            "",
            "def get_google_ads_creds():",
            "    return GOOGLE_ADS.data if GOOGLE_ADS else None",
            "",
            "def get_sendgrid_key():",
            "    return SENDGRID.get('api_key') if SENDGRID else None",
            "",
            "def get_stripe_keys():",
            "    if not STRIPE:",
            "        return None",
            "    return {",
            "        'api_key': STRIPE.get('api_key'),",
            "        'secret_key': STRIPE.get('secret_key')",
            "    }",
        ])
        
        config_content = "\n".join(config_lines)
        output_path.write_text(config_content)
        output_path.chmod(0o600)
        
        return str(output_path)
    
    def print_summary(self):
        """Print setup summary - ZERO EFFORT"""
        print("\n" + "="*60)
        print("📊 Marketing Automation Setup Summary")
        print("="*60)
        
        if self.ready:
            print("\n✅ ALL REQUIRED CREDENTIALS READY")
            print(f"\n  Configured Services ({len(self.credentials)}):")
            for service in self.credentials.keys():
                print(f"    • {service}")
        else:
            print("\n❌ SETUP INCOMPLETE")
            print(f"\n  Missing Credentials:")
            for missing in self.missing:
                print(f"    • {missing}")
        
        print("\n" + "="*60)


def main():
    """Main setup function - ZERO EFFORT"""
    print("∞ Bryan's Marketing Automation Setup ∞")
    print("="*60)
    
    setup = MarketingAutomationSetup()
    
    # Validate credentials
    if not setup.validate_all():
        print("\n❌ Setup incomplete. Please configure missing credentials.")
        print("\n  To add credentials:")
        print("    1. Place JSON files in ~/.abekeys/credentials/")
        print("    2. Example: ~/.abekeys/credentials/google_ads.json")
        print("    3. Run this script again")
        sys.exit(1)
    
    # Generate config files
    print("\n📝 Generating configuration files...")
    
    env_file = setup.generate_env_file()
    print(f"  ✅ Created: {env_file}")
    
    config_file = setup.generate_python_config()
    print(f"  ✅ Created: {config_file}")
    
    # Print summary
    setup.print_summary()
    
    print("\n🚀 Next Steps:")
    print("  1. Review generated config files")
    print("  2. Source .env.marketing in your shell:")
    print(f"     source {env_file}")
    print("  3. Import config in Python:")
    print(f"     from marketing_config import *")
    print("\n✅ Setup Complete - Ready for Marketing Automation!")
    print("\n∞ AbëONE ∞")


if __name__ == "__main__":
    main()

