/**
 * Complete Chrome Extension Development Workflow Example
 * 
 * Pattern: AEYON × ARLAX × REC × SEMANTIC × MV3 × ONE
 * 
 * Demonstrates complete operationalization of Chrome Extension development
 */

import {
  mv3Operationalizer,
  recSemanticEngine,
  aeyonExecutor,
  arlaxDeploymentManager,
  type RECSemanticQuery,
  type AEYONExecutionContext,
} from '../index'

/**
 * Example 1: Validate Existing Extension
 */
export async function validateExtension() {
  // Load manifest and code files
  const manifest = {
    manifest_version: 3,
    name: 'My Extension',
    version: '1.0.0',
    background: {
      service_worker: 'src/service-worker.js',
    },
    permissions: ['storage', 'alarms'],
  }

  const codeFiles = [
    `// Service worker code
chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
  chrome.storage.session.set({ lastActivity: Date.now() })
  return true
})`,
  ]

  // Validate against MV3
  const report = mv3Operationalizer.validateExtension(manifest, codeFiles)

  console.log('MV3 Compliance Report:')
  console.log(`  Compliant: ${report.compliant}`)
  console.log(`  Score: ${report.score}/100`)
  console.log(`  Issues: ${report.issues.length}`)
  console.log(`  Recommendations: ${report.recommendations.length}`)

  return report
}

/**
 * Example 2: Semantic Pattern Discovery
 */
export function discoverPatterns() {
  // Search for patterns by intent
  const statePatterns = mv3Operationalizer.semanticSearch('state management')
  console.log(`Found ${statePatterns.length} state management patterns`)

  // Get success patterns
  const successPatterns = mv3Operationalizer.getSuccessPatterns()
  console.log(`Total success patterns: ${successPatterns.length}`)

  // Get patterns by category
  const serviceWorkerPatterns = mv3Operationalizer.getPatternsByCategory('service_worker')
  console.log(`Service worker patterns: ${serviceWorkerPatterns.length}`)

  return {
    statePatterns,
    successPatterns,
    serviceWorkerPatterns,
  }
}

/**
 * Example 3: Generate Execution Plan with REC × SEMANTIC
 */
export function generateExecutionPlan() {
  const query: RECSemanticQuery = {
    intent: 'Build content blocking extension with privacy features',
    context: {
      currentArchitecture: 'mv3',
      chromeVersion: '120',
      useCase: 'content blocking',
      constraints: ['privacy', 'performance'],
    },
    constraints: [
      {
        type: 'privacy',
        requirement: 'No data leakage',
        priority: 'critical',
      },
      {
        type: 'performance',
        requirement: 'Fast blocking',
        priority: 'high',
      },
    ],
    expectedOutcome: 'Production-ready privacy-focused content blocker',
  }

  const plan = recSemanticEngine.processQuery(query)

  console.log('Execution Plan:')
  console.log(`  Steps: ${plan.steps.length}`)
  console.log(`  Patterns: ${plan.patterns.length}`)
  console.log(`  Complexity: ${plan.estimatedComplexity}`)
  console.log(`  Validation Checks: ${plan.validation.checks.length}`)

  plan.steps.forEach((step, index) => {
    console.log(`\nStep ${index + 1}: ${step.action}`)
    console.log(`  Pattern: ${step.pattern.name}`)
    console.log(`  Category: ${step.pattern.category}`)
    console.log(`  Priority: ${step.pattern.priority}`)
  })

  return plan
}

/**
 * Example 4: Complete Extension Development Workflow
 */
export async function developExtension() {
  const context: AEYONExecutionContext = {
    extensionPath: './my-extension',
    manifest: {
      manifest_version: 3,
      name: 'Privacy Blocker',
      version: '1.0.0',
      description: 'Privacy-focused content blocker',
      background: {
        service_worker: 'src/service-worker.js',
      },
      permissions: ['storage', 'alarms', 'declarativeNetRequest'],
      host_permissions: ['<all_urls>'],
    },
    codeFiles: new Map([
      [
        'src/service-worker.js',
        `// Service worker will be generated by AEYON executor`,
      ],
    ]),
    targetChromeVersion: '120',
    deploymentTarget: 'chrome-web-store',
  }

  // Execute complete workflow
  const result = await aeyonExecutor.execute(context)

  if (result.success) {
    console.log('✅ Extension development complete!')
    console.log(`  Steps executed: ${result.steps.length}`)
    console.log(`  MV3 Compliant: ${result.validation.mv3Compliant}`)
    console.log(`  Validation Score: ${result.validation.score}/100`)
    console.log(`  Build Artifacts: ${result.deployment.buildArtifacts.length}`)
  } else {
    console.error('❌ Extension development failed')
    result.errors.forEach((error) => {
      console.error(`  ${error.step}: ${error.message}`)
      if (error.fix) {
        console.log(`    Fix: ${error.fix}`)
      }
    })
  }

  return result
}

/**
 * Example 5: Deploy to Chrome Web Store
 */
export async function deployToStore() {
  // First, develop the extension
  const developmentResult = await developExtension()

  if (!developmentResult.success) {
    throw new Error('Extension development failed')
  }

  // Generate deployment configuration
  const deploymentConfig = arlaxDeploymentManager.generateDeploymentConfig(
    developmentResult.deployment,
    'chrome-web-store'
  )

  // Validate deployment readiness
  const readiness = arlaxDeploymentManager.validateDeploymentReadiness(deploymentConfig)

  if (readiness.ready) {
    console.log('✅ Ready for Chrome Web Store deployment')
    console.log(`  Store Listing: ${deploymentConfig.store?.listing.name}`)
    console.log(`  Category: ${deploymentConfig.store?.submission.category}`)
  } else {
    console.error('❌ Not ready for deployment')
    readiness.issues.forEach((issue) => {
      console.error(`  ${issue}`)
    })
  }

  return {
    config: deploymentConfig,
    readiness,
  }
}

/**
 * Example 6: Enterprise Deployment
 */
export async function deployToEnterprise() {
  const context: AEYONExecutionContext = {
    extensionPath: './enterprise-extension',
    manifest: {
      manifest_version: 3,
      name: 'Enterprise Extension',
      version: '1.0.0',
      background: {
        service_worker: 'src/service-worker.js',
      },
      permissions: ['storage', 'alarms'],
    },
    codeFiles: new Map(),
    deploymentTarget: 'enterprise',
  }

  const result = await aeyonExecutor.execute(context)

  if (result.success) {
    const deploymentConfig = arlaxDeploymentManager.generateDeploymentConfig(
      result.deployment,
      'enterprise'
    )

    console.log('✅ Enterprise deployment configuration ready')
    console.log(`  Distribution Method: ${deploymentConfig.enterprise?.distribution.method}`)
    console.log(`  Update URL: ${deploymentConfig.enterprise?.distribution.updateUrl}`)
  }

  return result
}

/**
 * Example 7: Get Code Template for Pattern
 */
export function getCodeTemplate() {
  // Get pattern
  const pattern = mv3Operationalizer.getPattern('sw-state-session-storage')

  if (pattern) {
    // Generate code template
    const code = mv3Operationalizer.generateCodeTemplate(pattern.id)

    console.log(`Pattern: ${pattern.name}`)
    console.log(`Description: ${pattern.description}`)
    console.log(`\nCode Template:\n${code}`)

    return code
  }

  return null
}

/**
 * Example 8: Check Architectural Shifts
 */
export function checkArchitecturalShifts() {
  const architectures = mv3Operationalizer.getArchitectures()

  console.log('MV2 → MV3 Architectural Shifts:')
  architectures.forEach((arch, index) => {
    console.log(`\n${index + 1}. ${arch.component}`)
    console.log(`   MV2: ${arch.mv2Pattern}`)
    console.log(`   MV3: ${arch.mv3Pattern}`)
    console.log(`   Consequence: ${arch.strategicConsequence}`)
  })

  return architectures
}

// Run examples
if (require.main === module) {
  console.log('Chrome Extension MV3 Operationalization Examples\n')

  // Example 1: Validate
  validateExtension().then(() => {
    console.log('\n---\n')

    // Example 2: Discover patterns
    discoverPatterns()
    console.log('\n---\n')

    // Example 3: Generate plan
    generateExecutionPlan()
    console.log('\n---\n')

    // Example 7: Get code template
    getCodeTemplate()
    console.log('\n---\n')

    // Example 8: Check shifts
    checkArchitecturalShifts()
  })
}

