from typing import Any
#!/usr/bin/env python3
"""
Load testing for TokenGuard microservice using Locust.

This implements the 4-step performance validation framework:
1. Define Performance Budget: <20ms p95, <30ms for 5000-char input
2. Benchmark Under Load: Simulate realistic traffic patterns
3. Profile for Hotspots: Identify performance bottlenecks
4. Optimize Strategically: Data-driven improvements
"""

from locust import HttpUser, task, between
import random


class TokenGuardUser(HttpUser):
    """Simulates a user of the TokenGuard API."""

    wait_time = between(0.1, 2.0)  # Realistic inter-request delays

    def on_start(self: Any) -> Any:
        """Initialize test data for realistic scenarios."""
        self.test_texts = self._generate_test_texts()

    def _generate_test_texts(self: Any) -> Any:
        """Generate realistic test texts of various lengths."""
        base_text = "This is a sample response that could be generated by an AI system. "

        return {
            "short": base_text * 2,  # ~150 chars
            "medium": base_text * 10,  # ~750 chars
            "long": base_text * 30,  # ~2250 chars
            "very_long": base_text * 80,  # ~6000 chars
        }

    @task(40)
    def prune_short_text_high_confidence(self: Any) -> Any:
        """Most common scenario: short text with high confidence."""
        payload = {"text": self.test_texts["short"], "confidence": random.uniform(0.8, 0.95)}

        with self.client.post("/v1/prune", json=payload, catch_response=True) as response:
            if response.status_code != 200:
                response.failure(f"Expected 200, got {response.status_code}")
            else:
                data = response.json()
                if data["action"] != "keep":
                    response.failure("Expected 'keep' action for high confidence short text")

    @task(25)
    def prune_medium_text_medium_confidence(self: Any) -> Any:
        """Medium text with borderline confidence."""
        payload = {"text": self.test_texts["medium"], "confidence": random.uniform(0.6, 0.8)}

        with self.client.post("/v1/prune", json=payload, catch_response=True) as response:
            if response.status_code != 200:
                response.failure(f"Expected 200, got {response.status_code}")

    @task(20)
    def prune_long_text_low_confidence(self: Any) -> Any:
        """Long text with low confidence - should be pruned."""
        payload = {"text": self.test_texts["long"], "confidence": random.uniform(0.3, 0.6)}

        with self.client.post("/v1/prune", json=payload, catch_response=True) as response:
            if response.status_code != 200:
                response.failure(f"Expected 200, got {response.status_code}")
            else:
                data = response.json()
                if data["action"] != "prune":
                    response.failure("Expected 'prune' action for low confidence long text")

    @task(10)
    def analyze_very_long_text(self: Any) -> Any:
        """Analysis endpoint with very long text."""
        payload = {"text": self.test_texts["very_long"], "confidence": random.uniform(0.4, 0.9)}

        with self.client.post("/v1/analyze", json=payload, catch_response=True) as response:
            if response.status_code != 200:
                response.failure(f"Expected 200, got {response.status_code}")

    @task(5)
    def health_check(self: Any) -> Any:
        """Health check endpoint."""
        with self.client.get("/health", catch_response=True) as response:
            if response.status_code != 200:
                response.failure(f"Health check failed with {response.status_code}")


if __name__ == "__main__":
    # Example of running this with specific parameters
    print("To run load tests:")
    print("locust -f load_test.py --host=http://localhost:8000")
    print("\nRecommended test scenarios:")
    print("1. Baseline: locust -f load_test.py --host=http://localhost:8000 -u 10 -r 2 -t 60s")
    print("2. Load test: locust -f load_test.py --host=http://localhost:8000 -u 50 -r 5 -t 300s")
    print(
        "3. Stress test: locust -f load_test.py --host=http://localhost:8000 -u 100 -r 10 -t 300s"
    )
